apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: logstash
  namespace: kube-system
  labels:
    k8s-app: logging
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:6.2.2
        ports:
        - containerPort: 4000
        livenessProbe:
          tcpSocket:
            port: 4000
          initialDelaySeconds: 60
          periodSeconds: 20
        env:
        - name: ES_VERSION
          value: 2.4.6
        volumeMounts:
          - name: config-volume
            mountPath: /usr/share/logstash/config
          - name: logstash-pipeline-volume
            mountPath: /usr/share/logstash/pipeline
        resources:
          limits:
            cpu:    1.0
            memory: 500Mi
          requests:
            cpu:    0.5
            memory: 300Mi
      volumes:
      - name: config-volume
        configMap:
          name: logging-configmap
          items:
            - key: logstash.yml
              path: logstash.yml
      - name: logstash-pipeline-volume
        configMap:
          name: logging-configmap
          items:
            - key: logstash.conf
              path: logstash.conf
---
kind: Service
apiVersion: v1
metadata:
  name: logstash
  namespace: kube-system
  labels:
    k8s-app: logging
spec:
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: 4000
  type: ClusterIP
